spring:
  datasource:
    # url : JDBC url 작성, MVCC=TRUE 는 권장사항이라 붙임
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # table 자동으로 create 해주는 설정 (보편적인 설정인듯)
      ddl-auto: create
    properties:
      hibernate:
        # show_sql 은 jpa sql 을 system.out 으로 출력 (운영에선 권장하지 않음)
        # show_sql: true
        format_sql: true

logging.level:
  # org.hibernate.SQL : debug 는 jpa sql 을 log 로 출력 (show_sql 과 조금 다름)
  org.hibernate.SQL: debug
  org.hibernate.type: trace